- name: Install duplicity - debian
  apt:
    name: "{{ duplicity_ubuntu_packages }}"
    state: latest
    force: yes

  when: ansible_os_family == "Debian"

- name: Install python paramiko
  pip:
    name: paramiko
    state: present
  when: ansible_os_family == "Debian"

- name: Install duplicity -arch
  pacman:
    name: "{{ duplicity_arch_packages }}"
    state: latest
    force: yes
  when: ansible_os_family == "Archlinux"

- name: Install duplicity - CentOS
  yum:
    name: "{{ duplicity_centos_packages }}"
    state: present
  notify: Start nginx
  when: ansible_os_family == "RedHat"

- name: Set GPG options Centos
  lineinfile:
    state: present
    path: "/root/.gnupg/gpg.conf"
    line: "{{ item }}"
    create: yes
  with_items:
    - "use-agent"
  notify: Reload GPG agent
  when: ansible_os_family == "RedHat"

- name: Set GPG options
  lineinfile:
    state: present
    path: "/root/.gnupg/gpg.conf"
    line: "{{ item }}"
    create: yes
  with_items:
    - "use-agent"
    - "pinentry-mode loopback"
  notify: Reload GPG agent
  when: ansible_os_family == "Debian"

- name: Set GPG agent options
  lineinfile:
    state: present
    path: "/root/.gnupg/gpg-agent.conf"
    line: "allow-loopback-pinentry"
    create: yes
  notify: Reload GPG agent

- name: Create backup directory
  file:
    path: "{{ backup_directory }}"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Private backends
  template:
    src: backup_config
    dest: "{{ backup_directory }}/{{ item.name }}.cf"
    mode: 0700
    owner: root
    group: root
  with_items: "{{ duplicity_backends|default(omit) }}"
  when: duplicity_backends is defined

- name: Group backends
  template:
    src: backup_config
    dest: "{{ backup_directory }}/{{ item.name }}.cf"
    mode: 0700
    owner: root
    group: root
  with_items: "{{ duplicity_group_backends|default(omit) }}"
  when: duplicity_group_backends is defined

- name: Copy scripts
  template:
    src: "{{ item }}"
    dest: "{{ backup_directory }}"
    owner: root
    group: root
    mode: 0755
  with_fileglob: "templates/backup_scripts/*"

- name: Set backups
  copy:
    src: "configs/{{ inventory_hostname }}/duplicity_configs/"
    dest: "{{ backup_directory }}"
    owner: root
    group: root
    mode: 0755

- name: Add duplicity cronjob
  template:
    src: cron_job
    dest: /etc/cron.d/duplicity
    mode: 0755
    owner: root
    group: root
